#!/usr/bin/env python3

# Basic Python script to parse ntp.conf into JSON structure and vice versa

import json
import sys
from typing import Any, List, Sequence, TypedDict


class NTPEntry(TypedDict, total=False):
    type: str
    address: str
    autokey: bool
    burst: bool
    iburst: bool
    prefer: bool
    key: int
    version: int
    minpoll: int
    maxpoll: int
    ttl: int


class NTPConfig(TypedDict):
    data: List[NTPEntry]
    etc: List[str]


ETC_MARKER = "### !!!SERVER LIST GOES HERE ###"
SERVER_ENTRIES = ["pool", "server", "peer", "broadcast", "manycastclient"]


def eprint(*args: Any, **kwargs: Any) -> None:
    print(*args, file=sys.stderr, **kwargs)


def parse_entry(entry: Sequence[str]) -> NTPEntry:
    ret: NTPEntry = {}

    # address is 2nd value in word list
    ret["address"] = entry[1]
    ret["type"] = entry[0]

    # check flags and options
    i = 2
    while i < len(entry):
        w = entry[i]

        if w in ["autokey", "burst", "iburst", "prefer"]:
            ret[w] = True
        elif w in ["key", "version", "minpoll", "maxpoll", "ttl"]:
            ret[w] = int(entry[i + 1])
            i += 1

        i += 1

    return ret


def print_entry(srv: NTPEntry) -> None:
    result = srv["type"] + " " + srv["address"]

    if srv.get("autokey", False):
        result += " autokey"
    elif "key" in srv:
        result += " key " + str(srv["key"])

    if srv.get("burst", False):
        result += " burst"
    if srv.get("iburst", False):
        result += " iburst"
    if srv.get("prefer", False):
        result += " prefer"

    if "version" in srv:
        result += " version " + str(srv["version"])
    if "minpoll" in srv:
        result += " minpoll " + str(srv["minpoll"])
    if "maxpoll" in srv:
        result += " maxpoll " + str(srv["maxpoll"])
    if "ttl" in srv:
        result += " ttl " + str(srv["ttl"])

    print(result)


def from_json() -> None:
    try:
        data: NTPConfig = json.load(sys.stdin)
    except ValueError:
        eprint("Invalid JSON")
        sys.exit(1)

    data_printed = False

    # list other strings first
    for item in data["etc"]:
        if item != ETC_MARKER:
            print(item)
        elif not data_printed and "data" in data:
            data_printed = True
            if data["data"]:
                for srv in data["data"]:
                    print_entry(srv)
            else:
                # Keep the insertion point in the config while the server list
                # is empty, so future servers return to the same location.
                print(ETC_MARKER)


def to_json() -> None:
    data: List[NTPEntry] = []
    etc: List[str] = []

    etc_marked = False

    for line in sys.stdin:
        # check if it is server description
        m = line.split()

        if line.strip() == ETC_MARKER:
            if not etc_marked:
                etc_marked = True
                etc.append(ETC_MARKER)
        elif len(m) > 0 and m[0] in SERVER_ENTRIES:
            if not etc_marked:
                etc_marked = True
                etc.append(ETC_MARKER)

            data.append(parse_entry(m))
        else:
            etc.append(line.strip())

    # Keep an insertion point even when the current config has no servers.
    if not etc_marked:
        etc.append(ETC_MARKER)

    result: NTPConfig = {"data": data, "etc": etc}

    json.dump(result, sys.stdout, indent=True)


def main() -> None:
    if len(sys.argv) > 1 and sys.argv[1] == "-s":
        from_json()
    else:
        to_json()


if __name__ == "__main__":
    main()
